seed: 3
training: True   # Whether to train a model or not

# Settings for stable-baselines RL algorithm
sb_config:
  total_timesteps: 40000
  check_pt_interval: 1000
  num_cpu: 1

# Policy settings
sb_policy:
  type: "MlpPolicy"
  net_arch: 
    - pi: [256, 128]    # Custom actor network
      vf: [256, 128]    # Value function network

# Specify environment
robosuite:
  env_id: "PressfitV2"
  robots: "Panda"
  gripper_types: "TetrapackGripper"
  use_camera_obs: false
  use_object_obs: True   # Torso obs
  has_renderer: True
  has_offscreen_renderer: false
  render_camera: "customview"
  control_freq: 20
  horizon: 1000
  camera_names: "customview"
  camera_heights: 48
  camera_widths: 48
  camera_depths: false
  reward_shaping: True
  controller_configs:
    type: "OSC_POSE"
    input_max: 1
    input_min: -20481
    output_max: [0.05, 0.05, 0.05, 0.5, 0.5, 0.5]
    output_min: [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5]
    kp: 300
    damping_ratio: 1
    impedance_mode: "variable_kp"
    kp_limits: [0, 500]
    kp_input_max: 1
    kp_input_min: 0
    damping_ratio_limits: [0, 2]
    position_limits: null
    orientation_limits: null
    uncouple_pos_ori: True
    control_delta: True
    interpolation: null
    ramp_ratio: 0.2
  

# Settings used for file handling and logging (save/load destination etc)
file_handling:
  # Logging with Tensorboard and saving trained models
  tb_log_folder: "./logs/ppo_pressfit_v2_tb"
  tb_log_name: "tb_model"
  save_model_folder: "./logs/trained_pressfitv2_model"
  save_model_filename: "model"
  # Loading of trained models
  load_model_folder: "./logs/trained_pressfitv2_models"
  load_model_filename: "model"
  # Path to model which should be continued to train
  continue_training_model_folder: "./logs/trained_pressfitv2_models"
  continue_training_model_filename: null       # is null when training a new model


